services:
  - type: web
    name: shoppykart-api
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
